service: s3-file-uploader

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev3
  region: ap-south-1

custom:
  fileUploadBucketName: ${self:service}-bucket-${self:provider.stage}-v2

plugins:
  - serverless-iam-roles-per-function

functions:
  s3FileUploader:
    handler: controllers/uploadFileController.handler
    name: s3-file-uploader
    description: This function handles file uploads to S3.
    timeout: 60 # seconds
    memorySize: 128 # mb
    events:
      - http:
          path: files/upload
          method: POST
    iamRoleStatements:
      - Effect: Allow
        Action:
          - "s3:Put*"
        Resource: "arn:aws:s3:::${self:custom.fileUploadBucketName}/"
    environment:
      FILE_UPLOAD_BUCKET_NAME: ${self:custom.fileUploadBucketName}

resources:
  Resources:
    FileBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.fileUploadBucketName}
        AccessControl: Private
