service: s3-file-uploader

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: ap-south-1

custom:
  fileUploadBucketName: s3-file-uploader-dev-serverlessdeploymentbucket-kge0lged157

resources:
  Resources:
    FileBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.fileUploadBucketName}
        AccessControl: PublicRead
