service: s3-file-uploader

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: ap-south-1

custom:
  BucketName: ${self.service}-bucket-${self.provider.stage}

resources:
  Resources:
    FileBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.BucketName}
        AccessControl: PublicRead
